#!/usr/bin/env python3
"""Fetch track metadata and album art for the ids in content.yaml.

    python refresh_music.py

Writes music.yaml and hanyuc.com/data/images/music/*.jpg, both committed, so
that build.py never touches the network and a Spotify outage cannot break a
build or a deploy. Re-run it only when the track list changes.

No credentials required: oEmbed is public, and the artist name comes from the
public embed page. If Spotify changes the shape of that page the artist is
simply omitted rather than the run failing.

Populating the list automatically from listening history is a different job.
/v1/me/top/tracks and /v1/me/player/recently-played are user-scoped, so they
need OAuth, which a static page cannot hold - it would have to run in CI with a
refresh token in the repo secrets. Notes if that ever gets built:

  - prefer top/tracks?time_range=short_term over recently-played; the latter
    includes skips and repeats
  - a failed token refresh must fall back to the committed music.yaml rather
    than failing the deploy
  - a commit pushed with the default GITHUB_TOKEN does not trigger other
    workflows, so such a job has to build and deploy itself
"""

from __future__ import annotations

import io
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

import yaml

ROOT = Path(__file__).parent
ART_DIR = ROOT / "hanyuc.com" / "data" / "images" / "music"
ART_REL = "data/images/music"
CACHE = ROOT / "music.yaml"
ART_PX = 128  # displayed at ~48px; 128 covers 2x screens

UA = {"User-Agent": "Mozilla/5.0 (compatible; hanyuc.com build script)"}


def fetch(url: str, timeout: int = 20) -> bytes:
    return urllib.request.urlopen(
        urllib.request.Request(url, headers=UA), timeout=timeout
    ).read()


def oembed(track_id: str) -> dict:
    """Official, unauthenticated. Title and album art."""
    target = urllib.parse.quote(
        f"https://open.spotify.com/track/{track_id}", safe=""
    )
    return json.loads(fetch(f"https://open.spotify.com/oembed?url={target}"))


def artist_and_duration(track_id: str) -> tuple[str, str]:
    """Unofficial: scraped from the embed page. Degrades to ('', '')."""
    try:
        html = fetch(f"https://open.spotify.com/embed/track/{track_id}").decode(
            "utf-8", "replace"
        )
        blob = re.search(
            r'<script id="__NEXT_DATA__" type="application/json">(.*?)</script>',
            html,
            re.S,
        )
        entity = json.loads(blob.group(1))["props"]["pageProps"]["state"]["data"][
            "entity"
        ]
        artists = ", ".join(a["name"] for a in entity.get("artists", []))
        ms = entity.get("duration") or 0
        length = f"{ms // 60000}:{ms // 1000 % 60:02d}" if ms else ""
        return artists, length
    except Exception as exc:  # noqa: BLE001 - any shape change is non-fatal
        print(f"    artist lookup failed ({exc.__class__.__name__}); continuing")
        return "", ""


def save_art(track_id: str, url: str) -> str:
    """Download and downscale the cover so the page serves no third-party images."""
    from PIL import Image

    ART_DIR.mkdir(parents=True, exist_ok=True)
    im = Image.open(io.BytesIO(fetch(url))).convert("RGB")
    im.thumbnail((ART_PX, ART_PX), Image.LANCZOS)
    out = ART_DIR / f"{track_id}.jpg"
    im.save(out, "JPEG", quality=82, optimize=True)
    return f"{ART_REL}/{track_id}.jpg"


def main() -> None:
    content = yaml.safe_load((ROOT / "content.yaml").read_text("utf-8"))
    ids = content.get("music") or []
    if not ids:
        sys.exit("content.yaml has no `music:` ids")

    tracks = []
    for track_id in ids:
        print(f"  {track_id}")
        try:
            meta = oembed(track_id)
        except urllib.error.HTTPError as exc:
            sys.exit(f"oEmbed failed for {track_id}: {exc}")
        artist, length = artist_and_duration(track_id)
        tracks.append(
            {
                "id": track_id,
                "title": meta["title"],
                "artist": artist,
                "length": length,
                "art": save_art(track_id, meta["thumbnail_url"]),
            }
        )
        print(f"    {meta['title']} - {artist or '(unknown artist)'} {length}")

    CACHE.write_text(
        "# Generated by refresh_music.py - do not edit by hand.\n"
        "# build.py reads this so it never needs the network.\n"
        + yaml.safe_dump({"tracks": tracks}, allow_unicode=True, sort_keys=False),
        "utf-8",
    )
    print(f"\nwrote {CACHE} ({len(tracks)} tracks)")
    print(f"wrote {ART_DIR}")


if __name__ == "__main__":
    main()
